src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $ProductName = null;

    #[ORM\Column(length: 255)]
    private ?string $ProductImages = null;

    #[ORM\Column]
    private ?float $NumberChapter = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $ProductDate = null;

    #[ORM\ManyToOne(inversedBy: 'products')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Tag $tag = null;

    #[ORM\ManyToOne(inversedBy: 'products')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Category $category = null;

    #[ORM\ManyToOne(inversedBy: 'products')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Author $author = null;

    #[ORM\OneToMany(mappedBy: 'product', targetEntity: Review::class)]
    private Collection $reviews;

    public function __construct()
    {
        $this->reviews = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProductName(): ?string
    {
        return $this->ProductName;
    }

    public function setProductName(string $ProductName): self
    {
        $this->ProductName = $ProductName;

        return $this;
    }

    public function getProductImages(): ?string
    {
        return $this->ProductImages;
    }

    public function setProductImages(string $ProductImages): self
    {
        $this->ProductImages = $ProductImages;

        return $this;
    }

    public function getNumberChapter(): ?float
    {
        return $this->NumberChapter;
    }

    public function setNumberChapter(float $NumberChapter): self
    {
        $this->NumberChapter = $NumberChapter;

        return $this;
    }

    public function getProductDate(): ?\DateTimeInterface
    {
        return $this->ProductDate;
    }

    public function setProductDate(\DateTimeInterface $ProductDate): self
    {
        $this->ProductDate = $ProductDate;

        return $this;
    }

    public function getTag(): ?Tag
    {
        return $this->tag;
    }

    public function setTag(?Tag $tag): self
    {
        $this->tag = $tag;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getAuthor(): ?Author
    {
        return $this->author;
    }

    public function setAuthor(?Author $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection<int, Review>
     */
    public function getReviews(): Collection
    {
        return $this->reviews;
    }

    public function addReview(Review $review): self
    {
        if (!$this->reviews->contains($review)) {
            $this->reviews->add($review);
            $review->setProduct($this);
        }

        return $this;
    }

    public function removeReview(Review $review): self
    {
        if ($this->reviews->removeElement($review)) {
            // set the owning side to null (unless already changed)
            if ($review->getProduct() === $this) {
                $review->setProduct(null);
            }
        }

        return $this;
    }


}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\Contact;
use App\Entity\Product;
use App\Form\ContactType;
use App\Form\CreateProductType;
use App\Repository\ReviewRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

class HomeController extends AbstractController
{
    #[Route('/home', name: 'app_home')]

    /**
     * @Route("/home/", name="get_product")
     */

    public function getproduct(ManagerRegistry $doctrine):Response
    {
        $products = $doctrine->getRepository('App\Entity\Product')->findAll();
        $categories = $doctrine->getRepository('App\Entity\category')->findAll();
//        $category=$doctrine->getRepository('App\Entity\category')->find($id);





        return $this->render('home/index.html.twig', ['products' => $products, 'categories' => $categories]);
    }

    /**

     * @Route("category/details/{id}", name="category_pages")
     */
    public
    function categoryAction(ManagerRegistry $doctrine,$id): Response
    {
        $category = $doctrine->getRepository('App\Entity\Category')->find($id);


        return $this->render('home/category_page.html.twig',[
            'category' => $category]);
    }


        /**
         * @Route("home/contact", name="contact", methods={"GET","POST"})
         */
        public
        function contactAction(Request $request, ManagerRegistry $doctrine)
        {
            $contact = new Contact();
            $form = $this->createForm(ContactType::class, $contact);

            $form->handleRequest($request);
            if ($form->isSubmitted() && $form->isValid()) {
                $em = $doctrine->getManager();
                $em->persist($contact);
                $em->flush();
                return $this->redirectToRoute('get_product',
                    ['id' => $contact->getId()]);

            }

            return $this->render('home/contact_page.html.twig', [
                'form' => $form->createView()
            ]);
        }







    /**
     * @Route("home/product/create", name="product_create_page", methods={"GET","POST"})
     */
    public function createproductAction(ManagerRegistry $doctrine,Request $request, SluggerInterface $slugger)
    { $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $product = new Product();
        $form = $this->createForm(CreateProductType::class, $product);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // upload file
            $productImage = $form->get('ProductImages')->getData();
            if ($productImage) {
                $originalFilename = pathinfo($productImage->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename . '-' . uniqid() . '.' . $productImage->guessExtension();

                // Move the file to the directory where brochures are stored
                try {
                    $productImage->move(
                        $this->getParameter('productImages_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    $this->addFlash(
                        'error',
                        'Cannot upload'
                    );// ... handle exception if something happens during file upload
                }
                $product->setProductImages($newFilename);
            }else{
                $this->addFlash(
                    'error',
                    'Cannot upload'
                );// ... handle exception if something happens during file upload
            }
            $em = $doctrine->getManager();
            $em->persist($product);
            $em->flush();

            $this->addFlash(
                'notice',
                'Product Added'
            );
            return $this->redirectToRoute('get_product');
        }
        return $this->renderForm('home/product_create.html.twig', ['form' => $form,]);
    }
}

templates/home/category_page.html.twig
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    <link rel="canonical" href="https://getbootstrap.com/docs/3.4/examples/starter-template/">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

    <title>{% block title %}Welcome!{% endblock %}</title>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.3/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>

    <!-- Bootstrap core CSS -->
    {#        <link href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" rel="stylesheet">#}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">



    {% block body %}
    <style>
        <style>
        *{
            margin:0;
            box-sizing: border-box;
        }
        .carousel-inner img {
            width: 100%;
            height: 100%;
        }

        .poly-prod{
            text-align:center;
            padding:5px;
        }

        .poly-prod .panel-body img{
            height: 150px;
            max-width: 95%;
        }

        /*footer*/
        .site-footer
        {
            background-color:#26272b;
            padding:45px 0 20px;
            font-size:15px;
            line-height:24px;
            color:#737373;
        }
        .site-footer hr
        {
            border-top-color:#bbb;
            opacity:0.5
        }
        .site-footer hr.small
        {
            margin:20px 0
        }
        .site-footer h6
        {
            color:#fff;
            font-size:16px;
            text-transform:uppercase;
            margin-top:5px;
            letter-spacing:2px
        }
        .site-footer a
        {
            color:#737373;
        }
        .site-footer a:hover
        {
            color:#3366cc;
            text-decoration:none;
        }
        .footer-links
        {
            padding-left:0;
            list-style:none
        }
        .footer-links li
        {
            display:block
        }
        .footer-links a
        {
            color:#737373
        }
        .footer-links a:active,.footer-links a:focus,.footer-links a:hover
        {
            color:#3366cc;
            text-decoration:none;
        }
        .footer-links.inline li
        {
            display:inline-block
        }
        .site-footer .social-icons
        {
            text-align:right
        }
        .site-footer .social-icons a
        {
            width:40px;
            height:40px;
            line-height:40px;
            margin-left:6px;
            margin-right:0;
            border-radius:100%;
            background-color:#33353d
        }
        .copyright-text
        {
            margin:0
        }
        @media (max-width:991px)
        {
            .site-footer [class^=col-]
            {
                margin-bottom:30px
            }
        }
        @media (max-width:767px)
        {
            .site-footer
            {
                padding-bottom:0
            }
            .site-footer .copyright-text,.site-footer .social-icons
            {
                text-align:center
            }
        }
        .social-icons
        {
            padding-left:0;
            margin-bottom:0;
            list-style:none
        }
        .social-icons li
        {
            display:inline-block;
            margin-bottom:4px
        }
        .social-icons li.title
        {
            margin-right:15px;
            text-transform:uppercase;
            color:#96a2b2;
            font-weight:700;
            font-size:13px
        }
        .social-icons a{
            background-color:#eceeef;
            color:#818a91;
            font-size:16px;
            display:inline-block;
            line-height:44px;
            width:44px;
            height:44px;
            text-align:center;
            margin-right:8px;
            border-radius:100%;
            -webkit-transition:all .2s linear;
            -o-transition:all .2s linear;
            transition:all .2s linear
        }
        .social-icons a:active,.social-icons a:focus,.social-icons a:hover
        {
            color:#fff;
            background-color:#29aafe
        }
        .social-icons.size-sm a
        {
            line-height:34px;
            height:34px;
            width:34px;
            font-size:14px
        }
        .social-icons a.facebook:hover
        {
            background-color:#3b5998
        }
        .social-icons a.twitter:hover
        {
            background-color:#00aced
        }
        .social-icons a.linkedin:hover
        {
            background-color:#007bb6
        }
        .social-icons a.dribbble:hover
        {
            background-color:#ea4c89
        }
        @media (max-width:767px)
        {
            .social-icons li.title
            {
                display:block;
                margin-right:0;
                font-weight:600
            }
        }
        .dropdown-item:focus, .dropdown-item:hover {
            color: #fff;
            text-decoration: none;
            background-color: #a9c6e3;
            font-weight: 400;}

    </style>


    <nav class="navbar navbar-expand-lg navbar-dark bg-dark w-100">
        <div class="container">
            <!-- Brand -->
            <a class="navbar-brand" href="{{ path('get_product') }}">
              NGUYỆT CÁT
            </a>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{{ path('get_product') }}">HOME</a>
                    </li>

                    <li class="nav-item active">
                        <a class="nav-link" href="{{ path('contact') }}">CONTACT</a>
                    </li>
                </ul>
            </div>
            <!-- Links -->
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">



                    <a class="nav-link" href="{{ path('app_login') }}">Login</a>

                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('register') }}">Register</a>
                    </li>

                    <!-- Dropdown -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                            UPLOAD <i class="fa fa-upload"></i>
                        </a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{{ path('review_create') }}">Review</a>
                            <a class="dropdown-item" href="{{ path('product_create_page') }}">Product</a>

                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

        <div class="container">


        <h2 class="page-header">{{ category.CatName }}</h2>
        <ul class="list-group">
            <li class="list-group-item"><h5>Description:</h5>{{ category.description }}</li>


        </ul>
            <div class="row">
            {% for product in category.products %}
                <div class = "poly-prod" style="width: calc(100%/3); float: left;   box-sizing: border-box;">
                    <div class = "panel panel-default" style="padding: -5px;">
                        <div class = "panel-heading" style="background-color: #ccc;">
                            <h4 class = "panel-title">
                                {{ product.productName }}
                            </h4>
                        </div>

                        <div class = "panel-body" >
                            <img src="{{ asset('upload/imageProduct/' ~ product.ProductImages) }}" height="228" width="292"/></div>
                        <div class = "panel-body" style="margin-top: 10px; margin-bottom: 0.5rem;">
                            <p>Author:  {{ product.author.AuthorName }} <br>
                                <span>Category:  </span>    {{ product.category.CatName}}</p>


                        </div>




                        <div class = "panel-footer" style="margin-bottom: 10px;">
                            <a href="{{path('review_product',{'id':product.id})}}" class="btn btn-success">Review</a>

                        </div>


                    </div>
                </div>
            {% endfor %}
            </div>

</div>


    {% endblock %}

    </body>
</html>

templates/home/history_blog.html.twig
{% block title %}Hello HomeController!{% endblock %}

{% block body %}
    {% for product in products %}

        <tr>
            <th scope="row">{{ product.id }}</th>
            <td>{{ product.productName }}</td>
        </tr>
    {% endfor %}

{% endblock %}

templates/home/index.html.twig
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    <link rel="canonical" href="https://getbootstrap.com/docs/3.4/examples/starter-template/">

    <title>{% block title %}Welcome!{% endblock %}</title>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.3/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">



    <!-- Bootstrap core CSS -->
{#        <link href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" rel="stylesheet">#}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

{#    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">#}
    {% block stylesheets %}{% endblock %}


</head>
<body>
{#{% block title %}Hello HomeController!{% endblock %}#}

{% block body %}
    <style>
    *{
        margin:0;
        box-sizing: border-box;
    }
    body {
        background-color: #eefafb;
    }
    .carousel-inner img {
        width: 100%;
        height: 100%;
    }

    .poly-prod{
        text-align:center;
        padding:5px;
    }

    .poly-prod .panel-body img{
        height: 150px;
        max-width: 95%;
    }

    section {
        width: 100%;
        display: inline-block;
        background: #333;
        height: 50vh;
        text-align: center;
        font-size: 22px;
        font-weight: 700;
        text-decoration: underline;
    }

    .footer-distributed{
        background: #666;
        box-shadow: 0 1px 1px 0 rgba(0, 0, 0, 0.12);
        box-sizing: border-box;
        width: 100%;
        text-align: left;
        font: bold 16px sans-serif;
        padding: 55px 50px;
    }

    .footer-distributed .footer-left,
    .footer-distributed .footer-center,
    .footer-distributed .footer-right{
        display: inline-block;
        vertical-align: top;
    }

    /* Footer left */

    .footer-distributed .footer-left{
        width: 40%;
    }

    /* The company logo */

    .footer-distributed h3{
        color:  #ffffff;
        font: normal 36px 'Open Sans', cursive;
        margin: 0;
    }

    .footer-distributed h3 span{
        color:  lightseagreen;
    }

    /* Footer links */

    .footer-distributed .footer-links{
        color:  #ffffff;
        margin: 20px 0 12px;
        padding: 0;
    }

    .footer-distributed .footer-links a{
        display:inline-block;
        line-height: 1.8;
        font-weight:400;
        text-decoration: none;
        color:  inherit;
    }

    .footer-distributed .footer-company-name{
        color:  #222;
        font-size: 14px;
        font-weight: normal;
        margin: 0;
    }

    /* Footer Center */

    .footer-distributed .footer-center{
        width: 35%;
    }

    .footer-distributed .footer-center i{
        background-color:  #33383b;
        color: #ffffff;
        font-size: 25px;
        width: 38px;
        height: 38px;
        border-radius: 50%;
        text-align: center;
        line-height: 42px;
        margin: 10px 15px;
        vertical-align: middle;
    }

    .footer-distributed .footer-center i.fa-envelope{
        font-size: 17px;
        line-height: 38px;
    }

    .footer-distributed .footer-center p{
        display: inline-block;
        color: #ffffff;
        font-weight:400;
        vertical-align: middle;
        margin:0;
    }

    .footer-distributed .footer-center p span{
        display:block;
        font-weight: normal;
        font-size:14px;
        line-height:2;
    }

    .footer-distributed .footer-center p a{
        color:  lightseagreen;
        text-decoration: none;;
    }

    .footer-distributed .footer-links a:before {
        content: "|";
        font-weight:300;
        font-size: 20px;
        left: 0;
        color: #fff;
        display: inline-block;
        padding-right: 5px;
    }

    .footer-distributed .footer-links .link-1:before {
        content: none;
    }

    /* Footer Right */

    .footer-distributed .footer-right{
        width: 20%;
    }

    .footer-distributed .footer-company-about{
        line-height: 20px;
        color:  #92999f;
        font-size: 13px;
        font-weight: normal;
        margin: 0;
    }

    .footer-distributed .footer-company-about span{
        display: block;
        color:  #ffffff;
        font-size: 14px;
        font-weight: bold;
        margin-bottom: 20px;
    }

    .footer-distributed .footer-icons{
        margin-top: 25px;
    }

    .footer-distributed .footer-icons a{
        display: inline-block;
        width: 35px;
        height: 35px;
        cursor: pointer;
        background-color:  #33383b;
        border-radius: 2px;

        font-size: 20px;
        color: #ffffff;
        text-align: center;
        line-height: 35px;

        margin-right: 3px;
        margin-bottom: 5px;
    }

    /* If you don't want the footer to be responsive, remove these media queries */

    @media (max-width: 880px) {

        .footer-distributed{
            font: bold 14px sans-serif;
        }

        .footer-distributed .footer-left,
        .footer-distributed .footer-center,
        .footer-distributed .footer-right{
            display: block;
            width: 100%;
            margin-bottom: 40px;
            text-align: center;
        }

        .footer-distributed .footer-center i{
            margin-left: 0;
        }

    }


    </style>

    <div id="demo" class="carousel slide" data-ride="carousel">

        <!-- Indicators -->
        <ul class="carousel-indicators">
            <li data-target="#demo" data-slide-to="0" class="active"></li>
            <li data-target="#demo" data-slide-to="1"></li>
            <li data-target="#demo" data-slide-to="2"></li>
        </ul>

        <!-- The slideshow -->
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{{ asset('upload/imageProduct/slider2.png' ) }}" alt="Los Angeles" width="1100" height="500">
            </div>
            <div class="carousel-item">
                <img src="{{ asset('upload/imageProduct/image2.jpg' ) }}" alt="Chicago" width="1100" height="500">
            </div>
            <div class="carousel-item">
                <img src="{{ asset('upload/imageProduct/image3.jpg' ) }}" alt="New York" width="1100" height="500">
            </div>
        </div>

        <!-- Left and right controls -->
        <a class="carousel-control-prev" href="#demo" data-slide="prev">
            <span class="carousel-control-prev-icon"></span>
        </a>
        <a class="carousel-control-next" href="#demo" data-slide="next">
            <span class="carousel-control-next-icon"></span>
        </a>
    </div>
{#menu#}

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark w-100">
        <div class="container">
            <!-- Brand -->
            <a class="navbar-brand" href="{{ path('get_product') }}">
              NGUYỆT CÁT
            </a>
<style>
    li:hover.nav-item{
        background-color: gray;
    }
    .dropdown-item:focus, .dropdown-item:hover {
        color: #fff;
        text-decoration: none;
        background-color: #a9c6e3;
        font-weight: 400;}
</style>
            <div class="collapse navbar-collapse menu" id="navbarSupportedContent" >
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item ">
                        <a class="nav-link" href="{{ path('get_product') }}">HOME</a>
                    </li>

                    <li class="nav-item ">
                        <a class="nav-link" href="{{ path('contact') }}">CONTACT</a>
                    </li>
                </ul>
            </div>
            <!-- Links -->
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">


                        <a class="nav-link" href="{{ path('app_login') }}">Login</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('register') }}">Register</a>
                    </li>

                    <!-- Dropdown -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                            UPLOAD <i class="fa fa-upload"></i>
                        </a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{{ path('review_create') }}">Review</a>
                            <a class="dropdown-item" href="{{ path('product_create_page') }}">Product</a>

                        </div>
                    </li>
                </ul>

            </div>
        </div>
    </nav>





<div class="row" style="margin-top: 20px;">

    <a href="" class="btn btn-success">REVIEW NOVELS</a>
</div>
    <div class="row" style="width: 100%; padding: 0; margin-top: 20px;margin-left: auto;margin-right: auto; min-height: 1500px; ">
        <div class="col-sm-9">
            {% for product in products %}
             <div class = "poly-prod" style="width: calc(100%/3); float: left;   box-sizing: border-box;">
                <div class = "panel panel-default" style="padding: -5px;">
                    <div class = "panel-heading" style="background-color: #ccc;">
                        <h4 class = "panel-title">
                            {{ product.productName }}
                        </h4>
                    </div>

                    <div class = "panel-body" >
                        <img src="{{ asset('upload/imageProduct/' ~ product.ProductImages) }}" height="228" width="292"/></div>
                    <div class = "panel-body" style="margin-top: 10px; margin-bottom: 0.5rem;">
                        <p>Author:  {{ product.author.AuthorName }} <br>
                        <span>Category:  </span>    {{ product.category.CatName}}</p>


                    </div>




                        <div class = "panel-footer" style="margin-bottom: 10px;">
                            <a href="{{path('review_product',{'id':product.id})}}" class="btn btn-success">Review</a>

                        </div>


                    </div>
                </div>
            {% endfor %}

        </div>

<div class="col-sm-3">
            <div class=" btn-group-vertical " style="width: 100%;" >
                <div class="panel-heading">
                    <span class = "glyphicon glyphicon-th-list"></span>
                    <strong>Chủng Loại</strong>
                </div>
                <div class="list-group"  style="min-width: 300px;">
                    {% for category in categories %}
                    <a href="{{ path('category_pages', {'id': category.id}) }} " class="list-group-item">{{ category.CatName }}</a>

                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <img src="{{ asset('upload/imageProduct/banner.jpg') }}" style="width: 100%;"
    </div>



    <footer class="footer-distributed">

        <div class="footer-left">

            <h3>Web<span>Nguyet Cat</span></h3>

            <p class="footer-links">
                <a href="{{ path('get_product') }}" class="link-1">Home</a>

                <a href="{{ path('contact') }}">Contact</a>

                <a href="{{ path('app_login') }}">Login</a>


                <a href="{{ path('register') }}">Register</a>


            </p>

            <p class="footer-company-name">Nguyet Cat © 2023</p>
        </div>

        <div class="footer-center">

            <div>
                <i class="fa fa-map-marker"></i>
                <p><span>30 Thich Quang Duc</span> Phu Nhuan, Ho Chi Minh City </p>
            </div>

            <div>
                <i class="fa fa-phone"></i>
                <p>+39 35195087</p>
            </div>

            <div>
                <i class="fa fa-envelope"></i>
                <p><a href="#">support@Nguyetcat.com</a></p>
            </div>

        </div>

        <div class="footer-right">

            <p class="footer-company-about">
                <span>About the website</span>
                Nguyet Cat helps users can view review the novels before deciding to read. This helps avoid reading novels that are unsuitable for them and introduce to them more fantastic novels.
            </p>

            <div class="footer-icons">

                <a href="#"><i class="fa fa-facebook"></i></a>
                <a href="#"><i class="fa fa-twitter"></i></a>
                <a href="#"><i class="fa fa-linkedin"></i></a>
                <a href="#"><i class="fa fa-github"></i></a>

            </div>

        </div>

    </footer>


{% endblock %}
</body>
</html>